proxy:
  title: ABMI Analysis Tools
  template-path: ./templates/2col
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: guest
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  # Example: 'ldap' authentication configuration
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base:
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: icarus
    display-name: ICARUS Viewer
    description: Immune/Inflammatory Diseases CDM Augmentation for Research Union System (ICARUS) Web-based INfographic Service (WINGS)
    container-cmd: ["R", "-e", "shiny::runApp('/root/icarusviewer/')"]
    container-image: icarusviewer:v0.1
    access-groups: scientists
  - id: aegis
    display-name: AEGIS
    description: Application for Epidemiological Geographic Information System (AEGIS). An open source spatial analysis tool based on CDM
    container-cmd: ["R", "-e", "shiny::runApp('/root/aegis/')"]
    container-image: aegis:v0.1
    access-groups: scientists
  - id: socratex
    display-name: SOCRATex
    description: Staged Optimization of Curation, Regularization, and Annotation of clinical Text
    container-cmd: ["R", "-e", "shiny::runApp('/root/socratex/')"]
    container-image: socratex:v0.1
    access-groups: scientists
  - id: gemini
    display-name: GEMINI
    description: Gemini means 'GEneral exaMINing and visualizing application for paired Institution'. It uses a connection of DB for extract a part of CDM data and makes rds files where you want.
    container-cmd: ["R", "-e", "shiny::runApp('/root/gemini/')"]
    container-image: gemini:v0.1
    access-groups: scientists
  - id: nlpsearchtool
    display-name: NLPSearchTool
    description: Test
    container-cmd: ["R", "-e", "shiny::runApp('/root/nlpsearchtool/')"]
    container-image: nlpsearchtool:v0.1
    access-groups: scientists

logging:
  file:
    shinyproxy.log